name: title

on:
  push:
    branches:
      - master
jobs:
  Source_Clear_Scan:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        env:
          JAVA_VERSION: 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - if: true
        run:
          echo "Hello manish"
  Build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        env:
          JAVA_VERSION: 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - run:
          bash echo "After set up Java"
  Push_to_Nexus:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        env:
          JAVA_VERSION: 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - if: true
        run: |
          bash echo "hello 1"
          bash echo "hello 2"
          bash echo "hello 3"


